### ISSUE TITLE
Issue - Add to cart success alert message is cached and displayed in account page, and few other irrelevant pages

### ISSUE THREAD

**Issue by amjtn** [litespeedtech/lscache-opencart#28]
Hello LiteSpeed Team,

Your plugin improves the OpenCart website performance to a great extent. Just a few issues alone

Issue with Basel theme - Add to cart success alert message is cached and displayed on the account page and a few other irrelevant pages. Please refer to this attachment

![LiteSpeed_Cache_Issue](https://github.com/litespeedtech/lscache-opencart/assets/7023443/f57bfede-ca5c-4585-9742-36cdba95c617)

OpenCart Version - 3.0.3.8 (https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance)
PHP Version - 8.1
LiteSpeed Plugin Used - https://github.com/litespeedtech/lscache-opencart/tree/master/3.0/upload

Kindly can you fix this Issue

Also, can you kindly add support for this theme (https://themeforest.net/item/basel-ajax-driven-opencart-theme/20199321) similar to the Journal theme

Thanks

**Comment by AndreyPopovNew** [comment]
same issue exist but resolved
https://github.com/litespeedtech/lscache-opencart/commit/4ec23f9917ae8aa1d23a278faf319ed3f0a7d250

may be some incompatibles with php 8.xx versions

are you try **disable** cache for 404 option?

**Comment by amjtn** [comment]
Hi,

Thank you for your reply

Issue persists with both Cache 404 Pages enabled and disabled

In admin page also showing Add to cart success alert message

Can you provide any solution to solve the same

Thanks

**Comment by AndreyPopovNew** [comment]
what server environment are you use?
LSWS (LiteSpeed Web Server) or OLS (OpenLiteSpeed)?

P.S. and remember - after **any change** of LSCache settings you must _**Purge All Caches**_

P.S.P.S. your theme Basel is
Last Update | 21 September 20**20**

are you sure Basel is full compatible with PHP 8.xx?

may be try PHP 7.3 or 7.4?

**Comment by amjtn** [comment]
LiteSpeed web server.
Not Open LiteSpeed

**Comment by AndreyPopovNew** [comment]
> LiteSpeed web server. Not Open LiteSpeed

are you use ESI feature?

and also enabled or disabled Ajax options for Shopcart/Wishlist/Compare?

**Comment by amjtn** [comment]
No ESI feature

Ajax Load Shopcart alone enabled
Wishlist and compare disabled

**Comment by AndreyPopovNew** [comment]
ESI disabled on General tab - yes?
all ESI features disabled on ESI Modules tab - yes?

what other settings?

Separate View for Logged-in Users ? on General
other Separate View?

on Page Settings tab Page cache for Login ?

**Comment by AndreyPopovNew** [comment]
and again: Basel theme
Version 1.3.1.0 
- Added support for Opencart 3.0.3.5 and 3.0.3.6
- Added support for PHP 7.4

you have Opencart 3.0.3.8 and PHP 8.1

**Comment by amjtn** [comment]
Hi,

Please find the details

a) General - LiteSpeed ESI Feature - Enabled
b) General - Separate View for All Options - Enabled
c) General - Ajax Load Shopcart - Enabled
d) Page Settings - Page Cache ( Login ) - Enabled for all Default Page Routes
e) ESI Modules - ESI Disabled for all ESI Module Routes	
f) Basel Theme:

_1) Scenario 1:_

OpenCart Version - 3.0.3.8 (https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance)
PHP Version - 8.1 or 7.4
Latest Basel Theme
LiteSpeed Cache Disabled

Result: No Errors Reported in Log & Also NO "Add to cart success alert message displayed on the account page and a few other irrelevant pages"

_2) Scenario 2:_

OpenCart Version - 3.0.3.8 (https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance)
PHP Version - 8.1 or 7.4
Latest Basel Theme
LiteSpeed Cache - Enabled with above options a) to e)

Result: No Errors Reported in Log
Issue ---> "Add to cart success alert message is displayed on the account page and a few other irrelevant pages"

Thanks

**Comment by AndreyPopovNew** [comment]
first:
b) General - Separate View for All Options - Enabled

in .htaccess uncommented LiteSpeed rewrite rules?

**Comment by amjtn** [comment]
### LITESPEED_CACHE_START - Do not remove this line
<IfModule LiteSpeed>
CacheLookup on
RewriteEngine On
RewriteCond %{REQUEST_URI} !/admin/ [NC]
## Uncomment the following directives if you has a separate mobile view
RewriteCond %{HTTP_USER_AGENT} "iPhone|iPod|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera Mini" [NC] 
RewriteRule .* - [E=Cache-Control:vary=isMobile]
## Uncomment the following directives if you has a separate Safari browser view
RewriteCond %{HTTP_USER_AGENT} Safari
RewriteCond %{HTTP_USER_AGENT} !Chrome
RewriteCond %{HTTP_USER_AGENT} !CriOS
RewriteRule .* - [E=Cache-Control:vary=isSafari]
## Uncomment the following directives only if enabled GUI Option of Separate Cache Copy for Mobile Device, "yoursite.domain" need to be changed
##RewriteCond %{HTTP_USER_AGENT} "iPhone|iPod|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera Mini" [NC] 
##RewriteCond %{HTTP_USER_AGENT} Bot
##RewriteRule .* - [CO=_lscache_vary:device\%3Amobile:yoursite.domain]
</IfModule>
### LITESPEED_CACHE_END

**Comment by AndreyPopovNew** [comment]
very hard to understand!!!!!!

but this rule
`RewriteCond %{REQUEST_URI} !/admin/ [NC]`
**not** in original plugin installation!!!!

P.S. after RewriteCond always must be RewriteRule!
otherwise RewriteCond combine with next RewriteCond like logical AND

P.S.P.S. also you must check thath LiteSpeed rewrite rules placed before any other rewrite rules (like Opencart SEO) with [L] flag

**Comment by amjtn** [comment]
If remove below line also same issue

RewriteCond %{REQUEST_URI} !/admin/ [NC]

**Comment by AndreyPopovNew** [comment]
if I seen - Login page modified by your theme
check **route paths** that used for these pages and try add these paths on URL Settings tab to 
Exclude URLs for logged-in users and/or Exclude URLs

**Comment by amjtn** [comment]
Even after excluding URLs for logged-in users also the Same issue persists

If LiteSpeed Cache is Enabled in Admin Page we are getting this alert message

![image](https://github.com/litespeedtech/lscache-opencart/assets/7023443/6a01cee9-9577-47a8-a2f0-139930d5cb8a)

**Comment by AndreyPopovNew** [comment]
post your whole .htaccess  (please use code tag on editor bar)

what SEO engine you use?

**Comment by amjtn** [comment]
``### LITESPEED_CACHE_START - Do not remove this line
<IfModule LiteSpeed>
CacheLookup on
RewriteEngine On
#RewriteCond %{REQUEST_URI} !/admin/ [NC]
## Uncomment the following directives if you has a separate mobile view
RewriteCond %{HTTP_USER_AGENT} "iPhone|iPod|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera Mini" [NC] 
RewriteRule .* - [E=Cache-Control:vary=isMobile]
## Uncomment the following directives if you has a separate Safari browser view
RewriteCond %{HTTP_USER_AGENT} Safari
RewriteCond %{HTTP_USER_AGENT} !Chrome
RewriteCond %{HTTP_USER_AGENT} !CriOS
RewriteRule .* - [E=Cache-Control:vary=isSafari]
## Uncomment the following directives only if enabled GUI Option of Separate Cache Copy for Mobile Device, "yoursite.domain" need to be changed
##RewriteCond %{HTTP_USER_AGENT} "iPhone|iPod|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera Mini" [NC] 
##RewriteCond %{HTTP_USER_AGENT} Bot
##RewriteRule .* - [CO=_lscache_vary:device\%3Amobile:yoursite.domain]
</IfModule>
### LITESPEED_CACHE_END

Options +FollowSymlinks

# Prevent Directory listing
Options -Indexes

# Deny access to all CGI, Perl, Python, Log, Ini, Text, Twig and Zip files
<FilesMatch ".(cgi|pl|py|log|ini|twig|zip)$">
Deny from all
</FilesMatch>

# Exclude robots.txt file alone from above block
<FilesMatch robots.txt>
Allow from all
</FilesMatch>

RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

RewriteBase /
RewriteRule ^sitemap.xml$ index.php?route=extension/feed/google_sitemap [L]
#RewriteRule ^googlebase.xml$ index.php?route=extension/feed/google_base [L]
RewriteRule ^google-feed$ index.php?route=extension/feed/google_base [L]
RewriteRule ^facebook-feed$ index.php?route=extension/feed/facebook_feed [L]
RewriteRule ^appcore/storage/(.*) index.php?route=error/not_found [L]
RewriteRule ^securestoragesvefiles/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

**Comment by AndreyPopovNew** [comment]
who add this to you .htaccess ?!?!?!!?!?!?!

I see

1. open tag <FilesMatch 
but **WHERE** close tag `</FilesMatch>`

2. "Deny from" all and next "Allow from all"  - for what    ??????

3. RewriteRule ^appcore/storage/(.) index.php?route=error/not_found [L]
RewriteRule ^securestoragesvefiles/(.) index.php?route=error/not_found [L]
but original is
`RewriteRule ^system/storage/(.*) index.php?route=error/not_found [L]`

4. RewriteCond %{REQUEST_URI} !..(ico|gif|jpg|jpeg|png|js|css)
but original
`RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)`

5. RewriteRule ^([^?]) index.php?route=$1 [L,QSA]
but original
`RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]`


**who makes these changes and for what?**


P.S. please use format tag CODE <> on editor tab for correct view of your post.
very difficult to understand where your mistakes and where editor re-format

**Comment by amjtn** [comment]
Hi,

Everything is correct in .htaccess file as you have mentioned

While pasting to this editor things were removed

Kindly check this screenshot

Thanks

![image](https://github.com/litespeedtech/lscache-opencart/assets/7023443/ef2ee982-ebdb-4e97-9e1d-1b3c210a47be)

**Comment by AndreyPopovNew** [comment]
for LiteSpeed exist recommendation

replace
`Options +FollowSymlinks`
to
`Option +SymLinksIfOwnerMatch`


another question

`# redirect all http to https`
`RewriteCond %{HTTPS} off`
`RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
?????????

and show other part of .htaccess
may be it contain another rules like `RewriteCond %{REQUEST_URI} !/admin/ [NC]` ;)


P.S. may be continue here: https://www.litespeedtech.com/support/forum/forums/litespeed-cache-extension-for-opencart.46/

**Comment by amjtn** [comment]
Hi,

Changed Options +FollowSymlinks to Option +SymLinksIfOwnerMatch

And Removed Below Mentioned Lines from Htaccess

RewriteCond %{REQUEST_URI} !/admin/ [NC]
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Still, Same Issue Persists

Thanks

**Comment by AndreyPopovNew** [comment]
until:
- full text .htaccess
- list of third party installed OC extensions
- screenshots of LSCache plugin settings
- site url

impossible qualification help to you

in support forum more possibilities to edit/format text and add images
