### ISSUE TITLE
Notice: Undefined index: language /extension/module/lscache.php on line 334

### ISSUE THREAD

**Issue by stevenmunro** [litespeedtech/lscache-opencart#8]
OpenCart 3.0.3.2

Fresh installation, default store. 
Installed "lscache-opencart3.0-V1.3.0.ocmod.zip" with default settings.

Along the top of the frontend I see this error.

`Notice: Undefined index: language in /data/redacted/domains/redacted.com/public_html/opencart/catalog/controller/extension/module/lscache.php on line 334`

and

`Notice: Undefined index: language in /data/redacted/domains/redacted.com/public_html/opencart/catalog/controller/extension/module/lscache.php on line 335`

**Comment by wuhua68** [comment]
Thanks for reporting, I just fixed it,  you can try download https://github.com/litespeedtech/lscache-opencart/blob/master/package/lscache-opencart3.0-latest.ocmod.zip  and test it again.

**Comment by stevenmunro** [comment]
Now getting this error;

`Warning: Cannot modify header information - headers already sent by (output started at /data/redacted/domains/redacted.com/public_html/opencart/catalog/controller/startup/error.php:34) in /data/redacted/domains/redacted.com/public_html/opencart/system/library/lscache/lscachebase.php on line 228`

**Comment by stevenmunro** [comment]
Scratch that. It was being caused because other errors for something else were also on the page.
